{{- $backendSecrets := coalesce .Values.backend.secrets .Values.backend.secretEnv (dict) -}}
{{- if $backendSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexora.fullname" . }}-backend
  labels:
{{ include "nexora.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := $backendSecrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}